Namespace: iris-ws
Container:
  Name: customer-ws
  ImageName: customer-ws
  ImageVersion: 1.0.7
  Ports:
  - 9990
  - 8080

Service:
  Ports:
  - Name: web-port
    Protocol: "TCP"
    Port: 8080
    TargetPort: 8080
    NodePort: 30980
  - Name: admin-port
    Protocol: "TCP"
    Port: 9990
    TargetPort: 9990
    NodePort: 30999
  Type: LoadBalancer