{{- with .Values.DB.Visualizer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ $.Values.Namespace }}
  labels:
    app: {{ .Name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
    spec:
      containers:
      - name: {{ .Container.Name }}
        image: {{ .Container.image | default "mongo-express" }}
        ports:
        - containerPort: {{ .Container.Port | default 8081 }}
        env:
        - name: ME_CONFIG_{{ $.Values.DB.Name | upper }}DB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.DB.Name }}-secret
              key: {{ $.Values.DB.Name | lower }}-root-username
        - name: ME_CONFIG_{{ $.Values.DB.Name | upper }}DB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.DB.Name }}-secret
              key: {{ $.Values.DB.Name | lower }}-root-password
        - name: ME_CONFIG_{{ $.Values.DB.Name | upper }}DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.DB.Name }}-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-service
  namespace: {{ $.Values.Namespace }}
spec:
  ports:
    - protocol: "TCP"
      port: {{ .TargetPort | default 8081 }}       
      targetPort: {{ .TargetPort | default 8081 }}  
      nodePort: {{ .NodePort }}
  type: LoadBalancer       
  selector:
    app: {{ .Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-internal-service
  namespace: {{ $.Values.Namespace }}
spec:
  ports:
    - protocol: {{ .Service.Protocol | default "TCP" }}
      port: {{ .Service.TargetPort | default 8081 }}
      targetPort: {{ .Service.TargetPort | default 8081 }}
  selector:
    app: {{ .Name }}

{{- end }}