apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.DB.Name }}-secret
    namespace: {{ .Values.Namespace }}
type: Opaque
data:
    {{ $.Values.DB.Name | lower }}-root-username: {{ .Values.DB.Username }}
    {{ $.Values.DB.Name | lower }}-root-password: {{ .Values.DB.Password }}