apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.DB.Name }}-deployment
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.DB.Name }}
spec:
  replicas: {{ .Values.DB.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.DB.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.DB.Name }}
    spec:
      containers:
      - name: {{ .Values.DB.Container.Name | default "mongo" }}
        image: {{ .Values.DB.Container.Image | default "mongo" }}
        ports:
        - containerPort: {{ .Values.DB.Container.Port | default 27017 }}
        env:
        - name: {{ $.Values.DB.Name | upper }}_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.DB.Name | lower }}-secret
              key: {{ $.Values.DB.Name | lower }}-root-username
        - name: {{ $.Values.DB.Name | upper }}_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.DB.Name | lower }}-secret
              key: {{ $.Values.DB.Name | lower }}-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.DB.Name }}-service
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - protocol: {{ .Values.DB.Service.Protocol | default "TCP" | quote | upper }} 
      port: {{ .Values.DB.Service.Port | default 27017 }}       
      targetPort: {{ .Values.DB.Service.TargetPort | default 27017 }}   
  selector:
    app: {{ .Values.DB.Name }}